--
-- PostgreSQL database dump
--

-- Dumped from database version 14.19 (Debian 14.19-1.pgdg13+1)
-- Dumped by pg_dump version 17.4

-- Started on 2025-09-04 20:50:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3421 (class 1262 OID 16384)
-- Name: banco_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE banco_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE banco_db OWNER TO postgres;

\connect banco_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 16386)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    cliente_id bigint NOT NULL,
    direccion character varying(255) NOT NULL,
    edad integer NOT NULL,
    genero character varying(255) NOT NULL,
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    contrasenia character varying(255) NOT NULL,
    estado boolean NOT NULL
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16385)
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN cliente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16395)
-- Name: cuentas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuentas (
    numero_cuenta character varying(255) NOT NULL,
    cliente_id bigint NOT NULL,
    estado boolean NOT NULL,
    saldo_inicial numeric(38,2) NOT NULL,
    tipo_cuenta character varying(255) NOT NULL
);


ALTER TABLE public.cuentas OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16403)
-- Name: movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos (
    id bigint NOT NULL,
    fecha date NOT NULL,
    numero_cuenta character varying(255) NOT NULL,
    saldo numeric(38,2) NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor numeric(38,2) NOT NULL
);


ALTER TABLE public.movimientos OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16402)
-- Name: movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3412 (class 0 OID 16386)
-- Dependencies: 210
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (cliente_id, direccion, edad, genero, identificacion, nombre, telefono, contrasenia, estado) FROM stdin;
1	Otavalo sn y principal	30	M	0102030405	Jose Lema	098254785	1234	t
2	Amazonas y NNUU	35	F	0243543236	Marianela Montalvo	097548965	5678	t
3	13 junio y Equinoccial	25	M	0690233022	Juan Osorio	098874587	1245	t
\.


--
-- TOC entry 3413 (class 0 OID 16395)
-- Dependencies: 211
-- Data for Name: cuentas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuentas (numero_cuenta, cliente_id, estado, saldo_inicial, tipo_cuenta) FROM stdin;
478758	1	t	2000.00	Ahorro
225487	2	t	100.00	Corriente
495878	3	t	0.00	Ahorros
496825	2	t	540.00	Ahorros
585545	1	t	1000.00	Corriente
\.


--
-- TOC entry 3415 (class 0 OID 16403)
-- Dependencies: 213
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimientos (id, fecha, numero_cuenta, saldo, tipo_movimiento, valor) FROM stdin;
1	2025-09-05	478758	1425.00	Retiro	-575.00
2	2025-09-05	225487	700.00	Depósito	600.00
3	2025-09-05	495878	150.00	Depósito	150.00
4	2025-09-05	496825	0.00	Retiro	-540.00
\.


--
-- TOC entry 3423 (class 0 OID 0)
-- Dependencies: 209
-- Name: clientes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_cliente_id_seq', 3, true);


--
-- TOC entry 3424 (class 0 OID 0)
-- Dependencies: 212
-- Name: movimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_id_seq', 4, true);


--
-- TOC entry 3264 (class 2606 OID 16392)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id);


--
-- TOC entry 3268 (class 2606 OID 16401)
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (numero_cuenta);


--
-- TOC entry 3270 (class 2606 OID 16409)
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 16394)
-- Name: clientes ukmvqpaay4xno9pnlalro0awadi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukmvqpaay4xno9pnlalro0awadi UNIQUE (identificacion);


--
-- TOC entry 3271 (class 2606 OID 16410)
-- Name: movimientos fko5koqjuegcyto02t8ytlf3y80; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fko5koqjuegcyto02t8ytlf3y80 FOREIGN KEY (numero_cuenta) REFERENCES public.cuentas(numero_cuenta);


--
-- TOC entry 3422 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2025-09-04 20:50:37

--
-- PostgreSQL database dump complete
--

